
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author balas
 */
public class AddStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form AddStudentForm
     */
    student std = new student();
    public AddStudentForm() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
	bg.add(male_radio);
	bg.add(female_radio);
	male_radio.setSelected(true);
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addstudent_label = new javax.swing.JLabel();
        address_label = new javax.swing.JLabel();
        firstname_label = new javax.swing.JLabel();
        lastname_label = new javax.swing.JLabel();
        gender_label = new javax.swing.JLabel();
        birthdate_label = new javax.swing.JLabel();
        phone_label = new javax.swing.JLabel();
        emergencyphone_textfield = new javax.swing.JTextField();
        firstname_textfield = new javax.swing.JTextField();
        lastname_textfield = new javax.swing.JTextField();
        female_radio = new javax.swing.JRadioButton();
        male_radio = new javax.swing.JRadioButton();
        date_chooser = new com.toedter.calendar.JDateChooser();
        add_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_textarea = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email_textfield = new javax.swing.JTextField();
        phone_textfield = new javax.swing.JTextField();
        phone_label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));
        setSize(new java.awt.Dimension(450, 700));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addstudent_label.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        addstudent_label.setText("Add Student");
        jPanel1.add(addstudent_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 190, 50));

        address_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        address_label.setText("Address            :");
        jPanel1.add(address_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 190, 30));

        firstname_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstname_label.setText("Firstname         :");
        jPanel1.add(firstname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 190, 30));

        lastname_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastname_label.setText("Lastname         :");
        jPanel1.add(lastname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 190, 30));

        gender_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gender_label.setText("Gender            :");
        jPanel1.add(gender_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 30));

        birthdate_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        birthdate_label.setText("Birthdate          :");
        jPanel1.add(birthdate_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, 30));

        phone_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phone_label.setText("Emergency Ph.   :");
        jPanel1.add(phone_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 200, 30));

        emergencyphone_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emergencyphone_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyphone_textfieldActionPerformed(evt);
            }
        });
        emergencyphone_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emergencyphone_textfieldKeyTyped(evt);
            }
        });
        jPanel1.add(emergencyphone_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 210, 30));

        firstname_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(firstname_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 210, 30));

        lastname_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(lastname_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, 30));

        female_radio.setBackground(new java.awt.Color(255, 255, 255));
        female_radio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        female_radio.setText("Female");
        female_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radioActionPerformed(evt);
            }
        });
        jPanel1.add(female_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 100, 30));

        male_radio.setBackground(new java.awt.Color(255, 255, 255));
        male_radio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        male_radio.setText("Male");
        jPanel1.add(male_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 90, 30));

        date_chooser.setFocusable(false);
        date_chooser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(date_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 210, 30));

        add_button.setBackground(new java.awt.Color(102, 102, 102));
        add_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 100, 30));

        cancel_button.setBackground(new java.awt.Color(252, 93, 93));
        cancel_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, -1, 30));

        address_textarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(address_textarea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 210, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("© Rafael Balaskas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, 110, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Email               :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 200, -1));

        email_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(email_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 210, 30));

        phone_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_textfieldActionPerformed(evt);
            }
        });
        phone_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_textfieldKeyTyped(evt);
            }
        });
        jPanel1.add(phone_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 210, 30));

        phone_label1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phone_label1.setText("Phone              :");
        jPanel1.add(phone_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void female_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_radioActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
       this.dispose();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void emergencyphone_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyphone_textfieldActionPerformed
        
    }//GEN-LAST:event_emergencyphone_textfieldActionPerformed

    private void emergencyphone_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emergencyphone_textfieldKeyTyped
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
	}
    }//GEN-LAST:event_emergencyphone_textfieldKeyTyped

    
    public boolean verifytext() {
	if (firstname_textfield.getText().equals("") || lastname_textfield.getText().equals("") 
                    || phone_textfield.getText().equals("")  || address_textarea.getText().equals("")
                    || date_chooser.getDate() == null || email_textfield.getText().equals("") || emergencyphone_textfield.getText().equals("")) {
			
                JOptionPane.showMessageDialog(null, "One Or More Empty Field!");
                return false;
	}
        else if(date_chooser.getDate().compareTo(new Date()) > 0){
                JOptionPane.showMessageDialog(null, "we are not allow student from the future!");
                return false;
        }
	else {
               return true;
	}
    }
    
    
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed

        String fname = firstname_textfield.getText();
        String lname = lastname_textfield.getText();
        
        String gender = "Male";
        if(female_radio.isSelected()) {
            gender = "Female";
        }
        String phone = phone_textfield.getText();
	String emergencyphone = emergencyphone_textfield.getText();
        String address = address_textarea.getText();
        String email = email_textfield.getText();
       
        
        if(verifytext()){
            SimpleDateFormat dateFormat = new SimpleDateFormat();
            String bdate = dateFormat.format(date_chooser.getDate());
            student std = new student();
            std.insertUpdateDeleteStudent('i', null, fname, lname, gender, bdate, phone, email, address, emergencyphone);
            Mainform.studentscount_label.setText(" Students count = "+Integer.toString(MyFunction.countData("student")));
           
        }
        try{
            manageStudentsForm.jTable1.setModel(new DefaultTableModel(null,new Object[]{"id","first_name", "last_name", "gender", "birthdate", "phone", "email", "address", "emergencyphone"}));
            std.fillStudentJtable(manageStudentsForm.jTable1, "");
            
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
                
        
	
    }//GEN-LAST:event_add_buttonActionPerformed

    private void phone_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_textfieldActionPerformed

    private void phone_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_textfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_textfieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel address_label;
    private javax.swing.JTextPane address_textarea;
    private javax.swing.JLabel addstudent_label;
    private javax.swing.JLabel birthdate_label;
    private javax.swing.JButton cancel_button;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JTextField emergencyphone_textfield;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.JLabel firstname_label;
    private javax.swing.JTextField firstname_textfield;
    private javax.swing.JLabel gender_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastname_label;
    private javax.swing.JTextField lastname_textfield;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JLabel phone_label;
    private javax.swing.JLabel phone_label1;
    private javax.swing.JTextField phone_textfield;
    // End of variables declaration//GEN-END:variables
}
