import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author balas
 */
public class EshopForm extends javax.swing.JFrame {

    /**
     * Creates new form EshopForm
     */
    Eshop es = new Eshop();
    student std = new student();
    DefaultTableModel model;
    public EshopForm() {
        initComponents();
        std.fillStudentJtable(jTable1, "");
        
        HideColumn(7);
        HideColumn(6);
        HideColumn(4);
        HideColumn(3);
        
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.gray);
        jTable1.setSelectionBackground(Color.black);
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    private void HideColumn(int ColIndex){
        TableColumn col = jTable1.getColumnModel().getColumn(ColIndex);
        col.setMaxWidth(0);
        col.setMinWidth(0);
        col.setPreferredWidth(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addstudent_label = new javax.swing.JLabel();
        buy_button = new javax.swing.JButton();
        id_label = new javax.swing.JLabel();
        Close_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        description_label = new javax.swing.JLabel();
        studentid_textfield = new javax.swing.JTextField();
        epikalamides_button = new javax.swing.JButton();
        tshirt_button = new javax.swing.JButton();
        short_button = new javax.swing.JButton();
        handwraps_button = new javax.swing.JButton();
        boxgloves_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        item_textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        size_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        price_textfield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        description_label1 = new javax.swing.JLabel();
        description_label2 = new javax.swing.JLabel();
        Code_textfield = new javax.swing.JTextField();
        Promitheutis_textfield = new javax.swing.JTextField();
        maselaki_button = new javax.swing.JButton();
        date_chooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 194, 123));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addstudent_label.setFont(new java.awt.Font("Tahoma", 1, 33)); // NOI18N
        addstudent_label.setText("  E-Shop");
        addstudent_label.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(addstudent_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 160, 50));

        buy_button.setBackground(new java.awt.Color(102, 102, 102));
        buy_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buy_button.setText("Buy");
        buy_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(buy_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 120, -1));

        id_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_label.setText("Student ID      :");
        jPanel1.add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        Close_button.setBackground(new java.awt.Color(255, 0, 0));
        Close_button.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Close_button.setText("Close");
        Close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, 110, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("© Rafael Balaskas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 670, 110, 20));

        description_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        description_label.setText("Code              :");
        jPanel1.add(description_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 30));

        studentid_textfield.setEditable(false);
        studentid_textfield.setBackground(new java.awt.Color(255, 255, 255));
        studentid_textfield.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        studentid_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentid_textfieldActionPerformed(evt);
            }
        });
        jPanel1.add(studentid_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 210, 30));

        epikalamides_button.setBackground(new java.awt.Color(153, 255, 153));
        epikalamides_button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        epikalamides_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eshop_images/epikalamides.jpeg"))); // NOI18N
        epikalamides_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                epikalamides_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(epikalamides_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 140, 90));

        tshirt_button.setBackground(new java.awt.Color(255, 51, 51));
        tshirt_button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tshirt_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eshop_images/tshirt.jpg"))); // NOI18N
        tshirt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tshirt_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(tshirt_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 140, 90));

        short_button.setBackground(new java.awt.Color(153, 153, 255));
        short_button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        short_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eshop_images/short.jpg"))); // NOI18N
        short_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                short_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(short_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 140, 90));

        handwraps_button.setBackground(new java.awt.Color(255, 102, 102));
        handwraps_button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        handwraps_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eshop_images/hand_wraps.jpg"))); // NOI18N
        handwraps_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handwraps_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(handwraps_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 140, 90));

        boxgloves_button.setBackground(new java.awt.Color(204, 204, 0));
        boxgloves_button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        boxgloves_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eshop_images/box_gloves.jpg"))); // NOI18N
        boxgloves_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxgloves_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(boxgloves_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 140, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Item              :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 180, 30));

        item_textfield.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        item_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_textfieldActionPerformed(evt);
            }
        });
        jPanel1.add(item_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 210, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Price              :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 40));

        size_textfield.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel1.add(size_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 210, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Size               :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 40));

        price_textfield.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jPanel1.add(price_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 210, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Firstname", "Lastname", "Gender", "Birthdate", "Phone", "Email", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 520, 310));

        description_label1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        description_label1.setText("Supplier          :");
        jPanel1.add(description_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 30));

        description_label2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        description_label2.setText("Date              :");
        jPanel1.add(description_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 30));

        Code_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Code_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 210, 30));

        Promitheutis_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(Promitheutis_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 210, 30));

        maselaki_button.setBackground(new java.awt.Color(153, 255, 153));
        maselaki_button.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        maselaki_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eshop_images/maselaki.jpeg"))); // NOI18N
        maselaki_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maselaki_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(maselaki_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 140, 90));

        date_chooser.setFocusable(false);
        date_chooser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(date_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buy_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_buttonActionPerformed

        int stdid = Integer.valueOf(studentid_textfield.getText());
        String itm = item_textfield.getText();
        int price = Integer.valueOf(price_textfield.getText());
        String size = size_textfield.getText();
        String Promitheutis = Promitheutis_textfield.getText();
        String Code = Code_textfield.getText();
    
        SimpleDateFormat dateFormat = new SimpleDateFormat();
        String date = dateFormat.format(date_chooser.getDate());
        

        es.insertUpdateDeleteStudent('i', stdid, itm, price, size, date, Promitheutis, Code);

        studentid_textfield.setText("");
        item_textfield.setText("");
        price_textfield.setText("");
        size_textfield.setText("");
        date_chooser.setDate(null);
        Promitheutis_textfield.setText("");
        Code_textfield.setText("");
    }//GEN-LAST:event_buy_buttonActionPerformed

    private void Close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_Close_buttonActionPerformed

    private void studentid_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentid_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentid_textfieldActionPerformed

    private void epikalamides_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_epikalamides_buttonActionPerformed
        item_textfield.setText("Shoes");
    }//GEN-LAST:event_epikalamides_buttonActionPerformed

    private void item_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_textfieldActionPerformed

    private void tshirt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tshirt_buttonActionPerformed
        item_textfield.setText("T-shirt");
    }//GEN-LAST:event_tshirt_buttonActionPerformed

    private void handwraps_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handwraps_buttonActionPerformed
        item_textfield.setText("Hand Wraps");
    }//GEN-LAST:event_handwraps_buttonActionPerformed

    private void boxgloves_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxgloves_buttonActionPerformed
       item_textfield.setText("Box Gloves");
       
    }//GEN-LAST:event_boxgloves_buttonActionPerformed

    private void short_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_short_buttonActionPerformed
        item_textfield.setText("Short");
    }//GEN-LAST:event_short_buttonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int rowindex = jTable1.getSelectedRow();
        studentid_textfield.setText(jTable1.getValueAt(rowindex, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

    }//GEN-LAST:event_jTable1KeyReleased

    private void maselaki_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maselaki_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maselaki_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EshopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EshopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EshopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EshopForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EshopForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close_button;
    private javax.swing.JTextField Code_textfield;
    private javax.swing.JTextField Promitheutis_textfield;
    private javax.swing.JLabel addstudent_label;
    private javax.swing.JButton boxgloves_button;
    private javax.swing.JButton buy_button;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JLabel description_label;
    private javax.swing.JLabel description_label1;
    private javax.swing.JLabel description_label2;
    private javax.swing.JButton epikalamides_button;
    private javax.swing.JButton handwraps_button;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField item_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JButton maselaki_button;
    private javax.swing.JTextField price_textfield;
    private javax.swing.JButton short_button;
    private javax.swing.JTextField size_textfield;
    private javax.swing.JTextField studentid_textfield;
    private javax.swing.JButton tshirt_button;
    // End of variables declaration//GEN-END:variables
}
