
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author balas
 */
public class Loginform extends javax.swing.JFrame {

    /**
     * Creates new form Loginform
     */
    public Loginform() {
        initComponents();
        username_star.setVisible(false);
        password_star.setVisible(false);
        
        JLabel l = new JLabel("<html>Follow the steps : <br/> <br/>1.  Open XAMPP Control Panel Program  (1/2) <br/> 2.  Press Start for Apache and MySQL     (2/2)  <br/> 3.   Ready to Login! </html>", SwingConstants.CENTER);
        l.setFont(new Font("Arial", Font.BOLD, 16));
        JOptionPane.showMessageDialog(null,l);
        
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        loginform_label = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        username_text = new java.awt.TextField();
        password_label = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        cancel_button = new java.awt.Button();
        login_button = new java.awt.Button();
        username_star = new javax.swing.JLabel();
        password_star = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        showpassword_radio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBounds(new java.awt.Rectangle(400, 300, 50, 50));
        setSize(new java.awt.Dimension(100, 100));

        panel.setBackground(new java.awt.Color(102, 102, 102));
        panel.setFocusCycleRoot(true);
        panel.setMinimumSize(new java.awt.Dimension(881, 384));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginform_label.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        loginform_label.setText("Login Form");
        panel.add(loginform_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 189, 74));

        username_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        username_label.setText("Password  : ");
        panel.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 40));

        username_text.setFont(new java.awt.Font("Dialog", 0, 19)); // NOI18N
        username_text.setName(""); // NOI18N
        panel.add(username_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 230, 30));

        password_label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        password_label.setText("Username : ");
        panel.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 34));

        password_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textActionPerformed(evt);
            }
        });
        panel.add(password_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 163, 230, 30));

        cancel_button.setBackground(new java.awt.Color(255, 51, 51));
        cancel_button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancel_button.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        cancel_button.setLabel("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        panel.add(cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 100, -1));

        login_button.setBackground(new java.awt.Color(0, 204, 0));
        login_button.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        login_button.setLabel("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        panel.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 240, 110, -1));

        username_star.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        username_star.setForeground(new java.awt.Color(255, 51, 51));
        username_star.setText("*");
        panel.add(username_star, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 106, 20, 24));

        password_star.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password_star.setForeground(new java.awt.Color(255, 51, 51));
        password_star.setText("*");
        panel.add(password_star, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("© Rafael Balaskas");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 110, 20));

        showpassword_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassword_radioActionPerformed(evt);
            }
        });
        panel.add(showpassword_radio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 20, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Show Password");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 713, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        if(username_text.getText().equals("")) {
           //username_star.setVisible(true);
           JOptionPane.showMessageDialog(null,"Username Field is Empty", null,2);
        }
        else if(String.valueOf(password_text.getPassword()).equals("")) {
            //password_star.setVisible(true);
            JOptionPane.showMessageDialog(null,"Password Field is Empty", null, 2);
        }
        else {

            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            try {
                ps = con.prepareStatement("SELECT * FROM user WHERE username = ? AND password = ?");

                ps.setString(1, username_text.getText());
                ps.setString(2, String.valueOf(password_text.getPassword()));

                ResultSet rs = ps.executeQuery();

                if(rs.next()) {
                    setVisible(false);
                    Mainform mf = new Mainform();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setTitle("Main Page");
                    mf.setLocationRelativeTo(null);
                    Mainform.welcome_label.setText("Welcome " + username_text.getText());
                    Mainform.studentscount_label.setText(" Student count = "+Integer.toString(MyFunction.countData("student")));
                    Mainform.coursesscount_label.setText(" Course count = "+Integer.toString(MyFunction.countData("course")));
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null,"Incorrect Username Or Password", "Login Failed", 2);
                }

            } catch (SQLException ea) {
                System.out.println(ea.getMessage());
            }
        }

    }//GEN-LAST:event_login_buttonActionPerformed

    private void password_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_textActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
       System.exit(0);
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void showpassword_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassword_radioActionPerformed
        if(showpassword_radio.isSelected()){
            password_text.setEchoChar((char)0);
        }
        else if(!(showpassword_radio.isSelected())){
             password_text.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassword_radioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button cancel_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Button login_button;
    private javax.swing.JLabel loginform_label;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel password_label;
    private javax.swing.JLabel password_star;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JRadioButton showpassword_radio;
    private javax.swing.JLabel username_label;
    private javax.swing.JLabel username_star;
    private java.awt.TextField username_text;
    // End of variables declaration//GEN-END:variables
}
