
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author balas
 */
public class Mainform extends javax.swing.JFrame {

    /**
     * Creates new form Mainform
     */
    
    public Mainform() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        currentDate();
        
    }

    private void currentDate(){
        Calendar cal = new GregorianCalendar();
        int day = cal.get(Calendar.DAY_OF_MONTH);
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        date_textfield.setText("Date : "+day + "/"+ (month+1) + "/" + year);
        
        int hour = cal.get(Calendar.HOUR_OF_DAY);
        int minutes = cal.get(Calendar.MINUTE);
        
        
        SimpleDateFormat sdf24 = new SimpleDateFormat("HH:mm");
        Date dat= cal.getTime();
        String date = sdf24.format(dat);
        time_textfield.setText("Time : "+date);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jPanel = new javax.swing.JPanel();
        welcome_label = new javax.swing.JLabel();
        studentscount_panel = new javax.swing.JPanel();
        coursesscount_label = new javax.swing.JLabel();
        studentscount_panel1 = new javax.swing.JPanel();
        studentscount_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        adduseditem_button = new javax.swing.JButton();
        addboughtitem_button = new javax.swing.JButton();
        addpayment_button = new javax.swing.JButton();
        addpresentation_button = new javax.swing.JButton();
        addstudent_button = new javax.swing.JButton();
        addcourse_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        time_textfield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date_textfield = new javax.swing.JTextField();
        id_and_names = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        addstudentmenuitem = new javax.swing.JMenuItem();
        managestudentmenuitem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        addcoursemenuitem = new javax.swing.JMenuItem();
        managecoursemenuitem = new javax.swing.JMenuItem();
        cashdesk = new javax.swing.JMenu();
        CashDesk_menuitem = new javax.swing.JMenuItem();
        showpayments = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        addpresentation = new javax.swing.JMenuItem();
        showpresentations = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        adduseditem_menuitem = new javax.swing.JMenuItem();
        showuseditems = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        buyitem_menuitem = new javax.swing.JMenuItem();
        showboughtitems_menuitem = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu7.setText("jMenu7");

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jLabel2.setText("jLabel2");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenu11.setText("jMenu11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(160, 160, 160));
        jPanel.setPreferredSize(new java.awt.Dimension(796, 665));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome_label.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        welcome_label.setText("Welcome <####>");
        jPanel.add(welcome_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 270, 47));

        studentscount_panel.setBackground(new java.awt.Color(0, 255, 204));

        coursesscount_label.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        coursesscount_label.setText("Courses count :");

        javax.swing.GroupLayout studentscount_panelLayout = new javax.swing.GroupLayout(studentscount_panel);
        studentscount_panel.setLayout(studentscount_panelLayout);
        studentscount_panelLayout.setHorizontalGroup(
            studentscount_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentscount_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coursesscount_label, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentscount_panelLayout.setVerticalGroup(
            studentscount_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentscount_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(coursesscount_label, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel.add(studentscount_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 260, 70));

        studentscount_panel1.setBackground(new java.awt.Color(153, 255, 153));

        studentscount_label.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        studentscount_label.setText("Students count : ");

        javax.swing.GroupLayout studentscount_panel1Layout = new javax.swing.GroupLayout(studentscount_panel1);
        studentscount_panel1.setLayout(studentscount_panel1Layout);
        studentscount_panel1Layout.setHorizontalGroup(
            studentscount_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentscount_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentscount_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        studentscount_panel1Layout.setVerticalGroup(
            studentscount_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentscount_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentscount_label, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel.add(studentscount_panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 260, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("© Rafael Balaskas");
        jPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, 110, 20));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel4.setText("K1 Fight Club Cy");
        jLabel4.setDoubleBuffered(true);
        jPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 351, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Help.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 75, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Click Here ");
        jPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        adduseditem_button.setBackground(new java.awt.Color(242, 242, 81));
        adduseditem_button.setText("Add Used Item");
        adduseditem_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduseditem_buttonActionPerformed(evt);
            }
        });
        jPanel.add(adduseditem_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 143, 75));

        addboughtitem_button.setBackground(new java.awt.Color(255, 204, 204));
        addboughtitem_button.setText("Add Bought Item");
        addboughtitem_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addboughtitem_buttonActionPerformed(evt);
            }
        });
        jPanel.add(addboughtitem_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 143, 75));

        addpayment_button.setBackground(new java.awt.Color(193, 106, 193));
        addpayment_button.setText("Add Payment");
        addpayment_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpayment_buttonActionPerformed(evt);
            }
        });
        jPanel.add(addpayment_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 143, 75));

        addpresentation_button.setBackground(new java.awt.Color(102, 153, 255));
        addpresentation_button.setText("Add Presentation");
        addpresentation_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpresentation_buttonActionPerformed(evt);
            }
        });
        jPanel.add(addpresentation_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 143, 75));

        addstudent_button.setBackground(new java.awt.Color(255, 126, 126));
        addstudent_button.setText("Add Student");
        addstudent_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudent_buttonActionPerformed(evt);
            }
        });
        jPanel.add(addstudent_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 143, 75));

        addcourse_button.setBackground(new java.awt.Color(91, 174, 91));
        addcourse_button.setText("Add Course");
        addcourse_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcourse_buttonActionPerformed(evt);
            }
        });
        jPanel.add(addcourse_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 143, 75));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Extra Informations");
        jPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        jLabel9.setText("__________________________________________");
        jPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Main Features");
        jPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel11.setText("____________________________________________________");
        jPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, -1, -1));

        time_textfield.setEditable(false);
        time_textfield.setBackground(new java.awt.Color(160, 160, 160));
        time_textfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        time_textfield.setBorder(null);
        time_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time_textfieldActionPerformed(evt);
            }
        });
        jPanel.add(time_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 122, -1));

        jLabel13.setText("_____________________________________________");
        jPanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        jLabel14.setText("_________________________________________________________");
        jPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setText("if you dont know the next step ");
        jPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        date_textfield.setEditable(false);
        date_textfield.setBackground(new java.awt.Color(160, 160, 160));
        date_textfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        date_textfield.setBorder(null);
        date_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_textfieldActionPerformed(evt);
            }
        });
        jPanel.add(date_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 122, -1));

        id_and_names.setBackground(new java.awt.Color(240, 155, 126));
        id_and_names.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        id_and_names.setText("IDs and NAMES");
        id_and_names.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_and_namesActionPerformed(evt);
            }
        });
        jPanel.add(id_and_names, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 170, 70));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setText("Click here to see all students");
        jPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 230, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel8.setText("ID and Names");
        jPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 110, -1));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));

        jMenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu5.setText("  Student");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        addstudentmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_student.jpg"))); // NOI18N
        addstudentmenuitem.setText("Add");
        addstudentmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentmenuitemActionPerformed(evt);
            }
        });
        jMenu5.add(addstudentmenuitem);

        managestudentmenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        managestudentmenuitem.setText("Manage");
        managestudentmenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managestudentmenuitemActionPerformed(evt);
            }
        });
        jMenu5.add(managestudentmenuitem);

        jMenuBar1.add(jMenu5);

        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu1.setText(" Course");
        jMenu1.setToolTipText("");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        addcoursemenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_course.png"))); // NOI18N
        addcoursemenuitem.setText("Add");
        addcoursemenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcoursemenuitemActionPerformed(evt);
            }
        });
        jMenu1.add(addcoursemenuitem);

        managecoursemenuitem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        managecoursemenuitem.setText("Manage");
        managecoursemenuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managecoursemenuitemActionPerformed(evt);
            }
        });
        jMenu1.add(managecoursemenuitem);

        jMenuBar1.add(jMenu1);

        cashdesk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cashdesk.setText(" Pay");

        CashDesk_menuitem.setText("Cash Desk");
        CashDesk_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashDesk_menuitemActionPerformed(evt);
            }
        });
        cashdesk.add(CashDesk_menuitem);

        showpayments.setText("Show Payments");
        showpayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpaymentsActionPerformed(evt);
            }
        });
        cashdesk.add(showpayments);

        jMenuBar1.add(cashdesk);

        jMenu10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu10.setText("  Presentations");

        addpresentation.setText("Add Presentation");
        addpresentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpresentationActionPerformed(evt);
            }
        });
        jMenu10.add(addpresentation);

        showpresentations.setText("Show Presentations");
        showpresentations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpresentationsActionPerformed(evt);
            }
        });
        jMenu10.add(showpresentations);

        jMenuBar1.add(jMenu10);

        jMenu6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu6.setText("  Used Items");

        adduseditem_menuitem.setText("Add Used Item");
        adduseditem_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduseditem_menuitemActionPerformed(evt);
            }
        });
        jMenu6.add(adduseditem_menuitem);

        showuseditems.setText("Show Used Items");
        showuseditems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showuseditemsActionPerformed(evt);
            }
        });
        jMenu6.add(showuseditems);

        jMenuBar1.add(jMenu6);

        jMenu12.setText("  E-Shop");

        buyitem_menuitem.setText("Buy Item");
        buyitem_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyitem_menuitemActionPerformed(evt);
            }
        });
        jMenu12.add(buyitem_menuitem);

        showboughtitems_menuitem.setText("Show Bought Items");
        showboughtitems_menuitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showboughtitems_menuitemActionPerformed(evt);
            }
        });
        jMenu12.add(showboughtitems_menuitem);

        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addstudentmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentmenuitemActionPerformed
        AddStudentForm addsf = new AddStudentForm();
        addsf.setVisible(true);
        addsf.pack();
        addsf.setTitle("Add Student Page");
        addsf.setLocationRelativeTo(null);
        addsf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addstudentmenuitemActionPerformed

    private void managestudentmenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managestudentmenuitemActionPerformed
        manageStudentsForm mngsf = new manageStudentsForm();
        mngsf.setVisible(true);
        mngsf.pack();
        mngsf.setTitle("Manage Student Page");
        mngsf.setLocationRelativeTo(null);
        mngsf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_managestudentmenuitemActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
      
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void addcoursemenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcoursemenuitemActionPerformed
        addCourseForm addcf = new addCourseForm();
        addcf.setVisible(true);
        addcf.pack();
        addcf.setTitle("Add Course Page");
        addcf.setLocationRelativeTo(null);
        addcf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addcoursemenuitemActionPerformed

    private void managecoursemenuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managecoursemenuitemActionPerformed
       
        manageCourseForm mcf = new manageCourseForm();
        mcf.setVisible(true);
        mcf.pack();
        mcf.setTitle("Mange Course Page");
        mcf.setLocationRelativeTo(null);
        mcf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_managecoursemenuitemActionPerformed

    
    private void CashDesk_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashDesk_menuitemActionPerformed
        PayForm pf = new PayForm();
        pf.setVisible(true);
        pf.pack();
        pf.setTitle("Cash Desk Page");
        pf.setLocationRelativeTo(null);
        pf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_CashDesk_menuitemActionPerformed

    private void showpaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpaymentsActionPerformed
        try {
            ShowPayments sp = new ShowPayments();
            sp.setVisible(true);
            sp.pack();
            sp.setTitle("Show Payments Page");
            sp.setLocationRelativeTo(null);
            sp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } catch (SQLException ex) {
            Logger.getLogger(Mainform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showpaymentsActionPerformed

    private void addpresentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpresentationActionPerformed
        PresentationForm ps = new PresentationForm();
        ps.setVisible(true);
        ps.pack();
        ps.setTitle("Add Presentations Page");
        ps.setLocationRelativeTo(null);
        ps.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addpresentationActionPerformed

    private void showpresentationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpresentationsActionPerformed
        ShowPresentations sps = new ShowPresentations();
        sps.setVisible(true);
        sps.pack();
        sps.setTitle("Show Presentations Page");
        sps.setLocationRelativeTo(null);
        sps.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_showpresentationsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "The System have the following feature :\n" + "1. Add Student or Manage Student. Check the First button at the tool bar\n" 
                                                                                        + "2. Add Course or Manage Course. Check the Second button at the tool bar\n"
                                                                                        + "3. Add Payment, See All Payments or See your Income. Check the Third button at the tool bar\n"
                                                                                        + "4. Add Presentation or See All Presentations. Check the Fourth button at the tool bar\n"
                                                                                        + "5. Add Used Item or See All Used Items. Check the Fifth button at the tool bar\n"
                                                                                        + "6. Add Bought Item or See All Bought Items and check your Income from E-shop. Check the Sixth button at the tool bar.\n\n"
                                                                                        +  "                                                               ! Attention !\n"
                                                                                        + "If you Click the Button Pay at Cash Desk Form you will send automatically email for Payment!\n"
                                                                                        + "Also if you Click the Button Add at Presentations Form you will send automatically email for Presentation!");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adduseditem_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduseditem_menuitemActionPerformed
        UsedItemForm esf = new UsedItemForm();
        esf.setVisible(true);
        esf.pack();
        esf.setTitle("Add Used Item Page");
        esf.setLocationRelativeTo(null);
        esf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_adduseditem_menuitemActionPerformed

    private void showuseditemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showuseditemsActionPerformed
        ShowUsedItems sui = new ShowUsedItems();
        sui.setVisible(true);
        sui.pack();
        sui.setTitle("Show Used Items");
        sui.setLocationRelativeTo(null);
        sui.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_showuseditemsActionPerformed

    private void buyitem_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyitem_menuitemActionPerformed
        EshopForm es = new EshopForm();
        es.setVisible(true);
        es.pack();
        es.setTitle("K1 Fight Club E-Shop");
        es.setLocationRelativeTo(null);
        es.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_buyitem_menuitemActionPerformed

    private void showboughtitems_menuitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showboughtitems_menuitemActionPerformed
        ShowBoughtItems sbi = new ShowBoughtItems();
        sbi.setVisible(true);
        sbi.pack();
        sbi.setTitle("Show Bought Items");
        sbi.setLocationRelativeTo(null);
        sbi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_showboughtitems_menuitemActionPerformed

    private void time_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_time_textfieldActionPerformed

    private void date_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_textfieldActionPerformed

    private void addstudent_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudent_buttonActionPerformed
        AddStudentForm addsf = new AddStudentForm();
        addsf.setVisible(true);
        addsf.pack();
        addsf.setTitle("Add Student Page");
        addsf.setLocationRelativeTo(null);
        addsf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addstudent_buttonActionPerformed

    private void addcourse_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcourse_buttonActionPerformed
        addCourseForm addcf = new addCourseForm();
        addcf.setVisible(true);
        addcf.pack();
        addcf.setTitle("Add Course Page");
        addcf.setLocationRelativeTo(null);
        addcf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addcourse_buttonActionPerformed

    private void addpayment_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpayment_buttonActionPerformed
        PayForm pf= new PayForm();
        pf.setVisible(true);
        pf.pack();
        pf.setTitle("Cash Desk Page");
        pf.setLocationRelativeTo(null);
        pf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addpayment_buttonActionPerformed

    private void adduseditem_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduseditem_buttonActionPerformed
        UsedItemForm esf = new UsedItemForm();
        esf.setVisible(true);
        esf.pack();
        esf.setTitle("Add Used Item Page");
        esf.setLocationRelativeTo(null);
        esf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_adduseditem_buttonActionPerformed

    private void addpresentation_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpresentation_buttonActionPerformed
        PresentationForm ps = new PresentationForm();
        ps.setVisible(true);
        ps.pack();
        ps.setTitle("Add Presentations Page");
        ps.setLocationRelativeTo(null);
        ps.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addpresentation_buttonActionPerformed

    private void addboughtitem_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addboughtitem_buttonActionPerformed
        EshopForm es = new EshopForm();
        es.setVisible(true);
        es.pack();
        es.setTitle("K1 Fight Club E-Shop");
        es.setLocationRelativeTo(null);
        es.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_addboughtitem_buttonActionPerformed

    private void id_and_namesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_and_namesActionPerformed
        id_and_names_table iant = new id_and_names_table();
        iant.setVisible(true);
        iant.pack();
        iant.setTitle("K1 Fight Club Students");
        iant.setLocationRelativeTo(null);
        iant.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_id_and_namesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CashDesk_menuitem;
    private javax.swing.JButton addboughtitem_button;
    private javax.swing.JButton addcourse_button;
    private javax.swing.JMenuItem addcoursemenuitem;
    private javax.swing.JButton addpayment_button;
    private javax.swing.JMenuItem addpresentation;
    private javax.swing.JButton addpresentation_button;
    private javax.swing.JButton addstudent_button;
    private javax.swing.JMenuItem addstudentmenuitem;
    private javax.swing.JButton adduseditem_button;
    private javax.swing.JMenuItem adduseditem_menuitem;
    private javax.swing.JMenuItem buyitem_menuitem;
    private javax.swing.JMenu cashdesk;
    public static javax.swing.JLabel coursesscount_label;
    private javax.swing.JTextField date_textfield;
    private javax.swing.JButton id_and_names;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel;
    private javax.swing.JMenuItem managecoursemenuitem;
    private javax.swing.JMenuItem managestudentmenuitem;
    private javax.swing.JMenuItem showboughtitems_menuitem;
    private javax.swing.JMenuItem showpayments;
    private javax.swing.JMenuItem showpresentations;
    private javax.swing.JMenuItem showuseditems;
    public static javax.swing.JLabel studentscount_label;
    private javax.swing.JPanel studentscount_panel;
    private javax.swing.JPanel studentscount_panel1;
    private javax.swing.JTextField time_textfield;
    public static javax.swing.JLabel welcome_label;
    // End of variables declaration//GEN-END:variables
}
