
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.ws.soap.MTOM;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author balas
 */
public class manageStudentsForm extends javax.swing.JFrame {

    /**
     * Creates new form manageStudentsForm
     */
    
    student std = new student();
    DefaultTableModel model;
    
    public manageStudentsForm() {
        initComponents();
        std.fillStudentJtable(jTable1, "");
        ButtonGroup bg = new ButtonGroup();
        bg.add(female_radio);
        bg.add(male_radio);
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.gray);
        jTable1.setSelectionBackground(Color.black);
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addstudent_label = new javax.swing.JLabel();
        address_label = new javax.swing.JLabel();
        entervalue_label = new javax.swing.JLabel();
        lastname_label = new javax.swing.JLabel();
        gender_label = new javax.swing.JLabel();
        birthdate_label = new javax.swing.JLabel();
        phone_label = new javax.swing.JLabel();
        phone_textfield = new javax.swing.JTextField();
        entervalue_textfield = new javax.swing.JTextField();
        lastname_textfield = new javax.swing.JTextField();
        female_radio = new javax.swing.JRadioButton();
        male_radio = new javax.swing.JRadioButton();
        date_chooser = new com.toedter.calendar.JDateChooser();
        add_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        edit_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        address_textarea = new javax.swing.JTextPane();
        firstname_label = new javax.swing.JLabel();
        firstname_textfield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        id_textfield = new javax.swing.JTextField();
        id_label = new javax.swing.JLabel();
        Close_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email_textfield = new javax.swing.JTextField();
        emergencyphone_textfield = new javax.swing.JTextField();
        phone_label1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(330, 160));

        jPanel1.setBackground(new java.awt.Color(237, 236, 151));

        addstudent_label.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        addstudent_label.setText("Manage Student");

        address_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        address_label.setText("Address     :");

        entervalue_label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        entervalue_label.setText("Enter value to search  :");

        lastname_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lastname_label.setText("Lastname  :");

        gender_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        gender_label.setText("Gender     :");

        birthdate_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        birthdate_label.setText("Birthdate   :");

        phone_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phone_label.setText("Phone       :");

        phone_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        phone_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_textfieldActionPerformed(evt);
            }
        });
        phone_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_textfieldKeyTyped(evt);
            }
        });

        entervalue_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entervalue_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entervalue_textfieldActionPerformed(evt);
            }
        });
        entervalue_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entervalue_textfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                entervalue_textfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                entervalue_textfieldKeyTyped(evt);
            }
        });

        lastname_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        female_radio.setBackground(new java.awt.Color(255, 255, 255));
        female_radio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        female_radio.setText("Female");
        female_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_radioActionPerformed(evt);
            }
        });

        male_radio.setBackground(new java.awt.Color(255, 255, 255));
        male_radio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        male_radio.setText("Male");

        date_chooser.setFocusable(false);
        date_chooser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        add_button.setBackground(new java.awt.Color(51, 153, 255));
        add_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        delete_button.setBackground(new java.awt.Color(255, 51, 51));
        delete_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete_button.setText("Remove");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        edit_button.setBackground(new java.awt.Color(102, 255, 153));
        edit_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edit_button.setText("Edit");
        edit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_buttonActionPerformed(evt);
            }
        });

        address_textarea.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(address_textarea);

        firstname_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        firstname_label.setText("Firstname  :");

        firstname_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        firstname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname_textfieldActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Firstname", "Lastname", "Gender", "Birthdate", "Phone", "Email", "Address", "Emergency ph."
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        id_textfield.setEditable(false);
        id_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_textfieldActionPerformed(evt);
            }
        });

        id_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_label.setText("      Id      :");

        Close_button.setBackground(new java.awt.Color(255, 0, 0));
        Close_button.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Close_button.setText("Close");
        Close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_buttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("© Rafael Balaskas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Email        :");

        email_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        email_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_textfieldActionPerformed(evt);
            }
        });

        emergencyphone_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emergencyphone_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyphone_textfieldActionPerformed(evt);
            }
        });

        phone_label1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        phone_label1.setText("Emerg. Ph.   :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(firstname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(firstname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lastname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(gender_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(birthdate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(phone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2)
                                                .addComponent(address_label, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(phone_label1)))
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lastname_textfield)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(male_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(20, 20, 20)
                                            .addComponent(female_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(date_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(phone_textfield)
                                        .addComponent(jScrollPane1)
                                        .addComponent(email_textfield)
                                        .addComponent(emergencyphone_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(entervalue_label, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(entervalue_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 134, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(243, 243, 243))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(addstudent_label, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addstudent_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(entervalue_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entervalue_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Close_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lastname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(gender_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(birthdate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(phone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lastname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(male_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(female_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(date_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(phone_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emergencyphone_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phone_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_textfieldActionPerformed

    }//GEN-LAST:event_phone_textfieldActionPerformed

    private void phone_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_textfieldKeyTyped
        if(!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_phone_textfieldKeyTyped

    private void female_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_radioActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        AddStudentForm addsf = new AddStudentForm();
        addsf.setVisible(true);
        addsf.pack();
        addsf.setLocationRelativeTo(null);
        addsf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_add_buttonActionPerformed

    
    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed

        /*
        ALTER TABLE score
        add CONSTRAINT fk_score_student
        FOREIGN KEY(`student_id`)
        REFERENCES student(id)
        on DELETE CASCADE
        */
        
        if(id_textfield.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No Student Selected");
        }
        
        int id = Integer.valueOf(id_textfield.getText());
        std.insertUpdateDeleteStudent('d', id, null, null, null, null, null,null, null,null);
        std.fillStudentJtable(jTable1, "");
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"id","first_name", "last_name", "gender", "birthdate", "phone", "email", "address","emergencyphone"}));
        std.fillStudentJtable(jTable1, entervalue_textfield.getText());
        Mainform.studentscount_label.setText(" Students count = "+Integer.toString(MyFunction.countData("student")));
        
        id_textfield.setText("");
        firstname_textfield.setText("");
        lastname_textfield.setText("");
	phone_textfield.setText("");
        emergencyphone_textfield.setText("");
        address_textarea.setText("");
        email_textfield.setText("");
        female_radio.setSelected(false);
        male_radio.setSelected(false);
        date_chooser.setDate(null);
       
    }//GEN-LAST:event_delete_buttonActionPerformed

    
    private void entervalue_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entervalue_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entervalue_textfieldActionPerformed

    private void firstname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname_textfieldActionPerformed

    
    public boolean verifytext() {
	if (firstname_textfield.getText().equals("") || lastname_textfield.getText().equals("") 
                    || phone_textfield.getText().equals("") || emergencyphone_textfield.getText().equals("") || address_textarea.getText().equals("")
                    || id_textfield.getText().equals("") ||date_chooser.getDate() == null) {
			
                JOptionPane.showMessageDialog(null, "One Or More Empty Field!");
                return false;
	}
        else if(date_chooser.getDate().compareTo(new Date()) > 0){
                JOptionPane.showMessageDialog(null, "we are not allow student from the future!");
                return false;
        }
	else {
               return true;
	}
    }
    
    
    private void edit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_buttonActionPerformed
        
        String fname = firstname_textfield.getText();
        String lname = lastname_textfield.getText();
        String phone = phone_textfield.getText();
        String emergencyphone = emergencyphone_textfield.getText();
        String email = email_textfield.getText();
        String address = address_textarea.getText();
        int id = Integer.valueOf(id_textfield.getText());
        String gender = "Male";
        if(female_radio.isSelected()) {
            gender = "Female";
        }

        if(verifytext()){
            SimpleDateFormat dateFormat = new SimpleDateFormat();
            String bdate = dateFormat.format(date_chooser.getDate());
            student std = new student();
            std.insertUpdateDeleteStudent('u', id, fname, lname, gender, bdate, phone, email, address, emergencyphone);
            //Mainform.studentscount_label.setText(" Students count = "+Integer.toString(MyFunction.countData("student")));
        
            manageStudentsForm.jTable1.setModel(new DefaultTableModel(null,new Object[]{"id","first_name", "last_name", "gender", "birthdate", "phone", "email", "address", "emergencyphone"}));
            std.fillStudentJtable(manageStudentsForm.jTable1, "");
        }
        
    }//GEN-LAST:event_edit_buttonActionPerformed

    int rowindex;
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        model = (DefaultTableModel)jTable1.getModel();
        
        int rowindex = jTable1.getSelectedRow();
        
        female_radio.setSelected(false);
        male_radio.setSelected(false);
        
        
        id_textfield.setText(model.getValueAt(rowindex, 0).toString());
        firstname_textfield.setText(model.getValueAt(rowindex, 1).toString());
        lastname_textfield.setText(model.getValueAt(rowindex, 2).toString());
        if(model.getValueAt(rowindex, 3).toString().equals("Male")){
            male_radio.setSelected(true);
        }
        else{
            female_radio.setSelected(true);
        }
        
        Date bdate;
        try {
            bdate = new SimpleDateFormat("MM/dd/yy").parse(model.getValueAt(rowindex, 4).toString());
            date_chooser.setDate(bdate);
        } catch (ParseException ex) {
            Logger.getLogger(manageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        phone_textfield.setText(model.getValueAt(rowindex, 5).toString());
        emergencyphone_textfield.setText(model.getValueAt(rowindex, 8).toString());
        email_textfield.setText(model.getValueAt(rowindex, 6).toString());
        address_textarea.setText(model.getValueAt(rowindex, 7).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void id_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_textfieldActionPerformed

    private void entervalue_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entervalue_textfieldKeyTyped
        
    }//GEN-LAST:event_entervalue_textfieldKeyTyped

    private void entervalue_textfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entervalue_textfieldKeyPressed
       
    }//GEN-LAST:event_entervalue_textfieldKeyPressed

    private void entervalue_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entervalue_textfieldKeyReleased
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"id","first_name", "last_name", "gender", "birthdate", "phone", "email", "address", "emergencyphone"}));
        std.fillStudentJtable(jTable1, entervalue_textfield.getText());
    }//GEN-LAST:event_entervalue_textfieldKeyReleased

    private void Close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_Close_buttonActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN){
            int rowindex = jTable1.getSelectedRow();
            
            id_textfield.setText(model.getValueAt(rowindex, 0).toString());
            firstname_textfield.setText(model.getValueAt(rowindex, 1).toString());
            lastname_textfield.setText(model.getValueAt(rowindex, 2).toString());
            if(model.getValueAt(rowindex, 3).toString().equals("Male")){
                male_radio.setSelected(true);
                female_radio.setSelected(false);
            }
            else{
                female_radio.setSelected(true);
                male_radio.setSelected(false);
            }
            
            Date bdate;
            try {
                bdate = new SimpleDateFormat("MM/dd/yy").parse(model.getValueAt(rowindex, 4).toString());
                date_chooser.setDate(bdate);
            } 
            catch (ParseException ex) {
                Logger.getLogger(manageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
            } 
            
            phone_textfield.setText(model.getValueAt(rowindex, 5).toString());
            emergencyphone_textfield.setText(model.getValueAt(rowindex, 8).toString());
            email_textfield.setText(model.getValueAt(rowindex, 6).toString());
            address_textarea.setText(model.getValueAt(rowindex, 7).toString());
            
              
        }       
    }//GEN-LAST:event_jTable1KeyReleased

    private void email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_textfieldActionPerformed

    private void emergencyphone_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyphone_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emergencyphone_textfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageStudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close_button;
    private javax.swing.JButton add_button;
    private javax.swing.JLabel address_label;
    private javax.swing.JTextPane address_textarea;
    private javax.swing.JLabel addstudent_label;
    private javax.swing.JLabel birthdate_label;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton edit_button;
    private javax.swing.JTextField email_textfield;
    private javax.swing.JTextField emergencyphone_textfield;
    private javax.swing.JLabel entervalue_label;
    private javax.swing.JTextField entervalue_textfield;
    private javax.swing.JRadioButton female_radio;
    private javax.swing.JLabel firstname_label;
    private javax.swing.JTextField firstname_textfield;
    private javax.swing.JLabel gender_label;
    private javax.swing.JLabel id_label;
    private javax.swing.JTextField id_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel lastname_label;
    private javax.swing.JTextField lastname_textfield;
    private javax.swing.JRadioButton male_radio;
    private javax.swing.JLabel phone_label;
    private javax.swing.JLabel phone_label1;
    private javax.swing.JTextField phone_textfield;
    // End of variables declaration//GEN-END:variables
}
