
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author balas
 */
public class ShowPayments extends javax.swing.JFrame {

    /**
     * Creates new form ShowPayments
     */
    Pay p = new Pay();
    DefaultTableModel model;
    
    public ShowPayments() throws SQLException {
        initComponents();
        p.showAllboughtitems(jTable1,entervalueforboughtitems_textfield.getText());
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.gray);
        jTable1.setSelectionBackground(Color.black);
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addstudent_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        calcyearly_button = new javax.swing.JButton();
        calcmonthly_button = new javax.swing.JButton();
        month_jComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        entervalueforboughtitems_textfield = new javax.swing.JTextField();
        entervalue_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(145, 235, 235));

        addstudent_label.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        addstudent_label.setText("All Payments");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Course Id", "Pay", "Month", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("© Rafael Balaskas");

        calcyearly_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calcyearly_button.setText("Calculate Yearly Income");
        calcyearly_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcyearly_buttonActionPerformed(evt);
            }
        });

        calcmonthly_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calcmonthly_button.setText("Calculate Monthly Income");
        calcmonthly_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcmonthly_buttonActionPerformed(evt);
            }
        });

        month_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        month_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January ", "February ", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_jComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Select Month to calculate Income for :");

        entervalueforboughtitems_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        entervalueforboughtitems_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entervalueforboughtitems_textfieldActionPerformed(evt);
            }
        });
        entervalueforboughtitems_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entervalueforboughtitems_textfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                entervalueforboughtitems_textfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                entervalueforboughtitems_textfieldKeyTyped(evt);
            }
        });

        entervalue_label.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        entervalue_label.setText("Enter value to search  :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addstudent_label, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(entervalue_label, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(entervalueforboughtitems_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calcyearly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(calcmonthly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(month_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addstudent_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entervalue_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entervalueforboughtitems_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(calcmonthly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(calcyearly_button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getSum(){
        int sum = 0;
        for (int i = 0; i<jTable1.getRowCount(); i++){
            sum = sum+ Integer.parseInt(jTable1.getValueAt(i, 4).toString());
        }
        JLabel label = new JLabel("Yearly income is : €"+ sum);
        label.setFont(new Font("Arial", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null,label );
    }
    
    void getMonthSum(){
        int sum = 0;
        for (int i = 0; i<jTable1.getRowCount(); i++){
            if(jTable1.getValueAt(i, 3).toString().equals(month_jComboBox.getSelectedItem().toString())){
                sum = sum+ Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            }
        }
        JLabel label = new JLabel("Income for month " + month_jComboBox.getSelectedItem().toString() + " is : €"+ sum);
        label.setFont(new Font("Arial", Font.BOLD, 18));
        JOptionPane.showMessageDialog(null,label );
    }
    
    
    private void calcyearly_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcyearly_buttonActionPerformed
        getSum();
    }//GEN-LAST:event_calcyearly_buttonActionPerformed

    private void calcmonthly_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcmonthly_buttonActionPerformed
        getMonthSum();
    }//GEN-LAST:event_calcmonthly_buttonActionPerformed

    private void month_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_month_jComboBoxActionPerformed

    private void entervalueforboughtitems_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entervalueforboughtitems_textfieldActionPerformed

    }//GEN-LAST:event_entervalueforboughtitems_textfieldActionPerformed

    private void entervalueforboughtitems_textfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entervalueforboughtitems_textfieldKeyPressed

    }//GEN-LAST:event_entervalueforboughtitems_textfieldKeyPressed

    private void entervalueforboughtitems_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entervalueforboughtitems_textfieldKeyReleased
        jTable1.setModel(new DefaultTableModel(null,new Object[]{"Student id", "Course id", "Pay", "Description","Amount"}));
        try {
            p.showAllboughtitems(jTable1, entervalueforboughtitems_textfield.getText());
        } catch (SQLException ex) {
            Logger.getLogger(ShowPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_entervalueforboughtitems_textfieldKeyReleased

    private void entervalueforboughtitems_textfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entervalueforboughtitems_textfieldKeyTyped

    }//GEN-LAST:event_entervalueforboughtitems_textfieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowPayments().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ShowPayments.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addstudent_label;
    private javax.swing.JButton calcmonthly_button;
    private javax.swing.JButton calcyearly_button;
    private javax.swing.JLabel entervalue_label;
    private javax.swing.JTextField entervalueforboughtitems_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> month_jComboBox;
    // End of variables declaration//GEN-END:variables
}
