import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author balas
 */
public class UsedItemForm extends javax.swing.JFrame {

    /**
     * Creates new form EShopForm
     */
    
    
    course c = new course();
    student std = new student();
    UsedItems es = new UsedItems();
    
    DefaultTableModel model;
    public UsedItemForm() {
        initComponents();
        c.fillCourseCombo(courseid_combobox);
        std.fillStudentJtable(jTable1, "");
        
        HideColumn(7);
        HideColumn(6);
        HideColumn(5);
        HideColumn(4);
        HideColumn(3);
        
        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.gray);
        jTable1.setSelectionBackground(Color.black);
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
    }

    private void HideColumn(int ColIndex){
        TableColumn col = jTable1.getColumnModel().getColumn(ColIndex);
        col.setMaxWidth(0);
        col.setMinWidth(0);
        col.setPreferredWidth(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addstudent_label = new javax.swing.JLabel();
        coursename_label = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        hours_label = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        Close_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        useditem_jComboBox = new javax.swing.JComboBox<>();
        courseid_combobox = new javax.swing.JComboBox<>();
        description_label = new javax.swing.JLabel();
        studentid_textfield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        date_chooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(237, 236, 151));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addstudent_label.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        addstudent_label.setText("Used Items");
        jPanel1.add(addstudent_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 270, 50));

        coursename_label.setBackground(new java.awt.Color(237, 236, 151));
        coursename_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        coursename_label.setText("Course Name    :");
        coursename_label.setOpaque(true);
        jPanel1.add(coursename_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        add_button.setBackground(new java.awt.Color(0, 204, 51));
        add_button.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 100, -1));

        hours_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hours_label.setText("Used Item        :");
        jPanel1.add(hours_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        id_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        id_label.setText("Id                   :");
        jPanel1.add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        Close_button.setBackground(new java.awt.Color(255, 0, 0));
        Close_button.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Close_button.setText("Close");
        Close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(Close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 97, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("© Rafael Balaskas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 110, 20));

        useditem_jComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        useditem_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gantia", "Gazes", "Epikalamides", "Maselaki", "Pantelonaki", "Mplouza" }));
        useditem_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useditem_jComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(useditem_jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 109, 37));

        courseid_combobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(courseid_combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 210, 36));

        description_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        description_label.setText("Date                :");
        jPanel1.add(description_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        studentid_textfield.setEditable(false);
        studentid_textfield.setBackground(new java.awt.Color(255, 255, 255));
        studentid_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentid_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentid_textfieldActionPerformed(evt);
            }
        });
        jPanel1.add(studentid_textfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 210, 38));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Firstname", "Lastname", "Gender", "Birthdate", "Phone", "Email", "Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 470, 290));

        date_chooser.setFocusable(false);
        date_chooser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(date_chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed

       int stdid = Integer.valueOf(studentid_textfield.getText());
       int crsid = Integer.valueOf(c.getcourseid(courseid_combobox.getSelectedItem().toString()));
       String used_item = String.valueOf(useditem_jComboBox.getSelectedItem().toString());
       SimpleDateFormat dateFormat = new SimpleDateFormat();
       String date = dateFormat.format(date_chooser.getDate());
       
       es.insertUpdateDeleteStudent('i', stdid, crsid, used_item, date);
       
       studentid_textfield.setText("");
       date_chooser.setDate(null);

    }//GEN-LAST:event_add_buttonActionPerformed

    private void Close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_buttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_Close_buttonActionPerformed

    private void useditem_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useditem_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useditem_jComboBoxActionPerformed

    private void studentid_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentid_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentid_textfieldActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int rowindex = jTable1.getSelectedRow();
        studentid_textfield.setText(jTable1.getValueAt(rowindex, 0).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased

    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsedItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsedItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsedItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsedItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsedItemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close_button;
    private javax.swing.JButton add_button;
    private javax.swing.JLabel addstudent_label;
    private javax.swing.JComboBox<String> courseid_combobox;
    private javax.swing.JLabel coursename_label;
    private com.toedter.calendar.JDateChooser date_chooser;
    private javax.swing.JLabel description_label;
    private javax.swing.JLabel hours_label;
    private javax.swing.JLabel id_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField studentid_textfield;
    private javax.swing.JComboBox<String> useditem_jComboBox;
    // End of variables declaration//GEN-END:variables
}
